services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d app"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - crypto_network
    profiles:
      - L1
      - services
      - L2
  
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - "16686:16686"
      - "4318:4318"
    networks:
      - crypto_network
    profiles:
      - L1
      - services
      - L2

  service_coin:
    build:
      context: .
      dockerfile: deploy/coin/dockerfile
    ports:
      - "9001:9001"
    environment:
      COIN_GECKO_TOKEN: ${COIN_GECKO_TOKEN}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - crypto_network
    profiles:
      - services
      - L2

networks:
  crypto_network:
    driver: bridge