version: '3'

tasks:
  test:
    desc: run all crypto_service tests
    cmds:
      - go test -count=1 ./...

  run:
    desc: run main.go
    cmds:
      - go run cmd/app/main.go

  up:
    desc: docker compose up
    cmds:
      - docker compose up -d

  down:
    desc: docker compose down
    cmds:
      - docker compose down

  test_l1:
    cmds:
      - docker compose --profile L1 down -v
      - docker compose --profile L1 up -d
      - sleep 10
      - task: migrate:up
      - export $(grep -v '^#' .env | xargs) && go test -v -tags=TEST_L1 ./...
      - docker compose --profile L1 down -v

  migrate:up:
    desc: db migration up
    cmds:
      - migrate -source file://migrations/postgres -database postgres://postgres:postgres@localhost:5432/app?sslmode=disable up

  migrate:down:
    desc: db migration down
    cmds:
      - migrate -source file://migrations/postgres -database postgres://postgres:postgres@localhost:5432/app?sslmode=disable down

  storage:drop:
    desc: db migration drop
    cmds:
      - migrate -source file://migrations/postgres -database postgres://postgres:postgres@localhost:5432/app?sslmode=disable drop

  