version: "3"

tasks:
  all:tests:
    desc: run all crypto_service tests
    cmds:
      - go test -count=1 ./...
      - task: test_l1

  run:
    desc: run main.go
    cmds:
      - go run cmd/app/main.go --config=./config/coin.yaml

  up:
    desc: docker compose up
    vars:
      ACTIVE_PROFILE: '{{.PROFILE | default "--profile services"}}'
    cmds:
      - docker compose --profile services up -d
      - |
        until docker compose --profile services exec -T db pg_isready -h localhost -U postgres -p 5432; do
          echo "Waiting for Postgres..."
          sleep 1
        done
      - echo "Postgres is up!"
      - migrate -source file://migrations/postgres -database "postgres://postgres:postgres@localhost:5432/app?sslmode=disable" up
      - docker compose {{.ACTIVE_PROFILE}} up -d --build

  down:
    desc: docker compose down
    vars:
      PROFILE: '{{.PROFILE | default ""}}'
    cmds:
      - migrate -source file://migrations/postgres -database "postgres://postgres:postgres@localhost:5432/app?sslmode=disable" drop -f
      - docker compose {{.PROFILE}} down

  test_l1:
    dotenv: [".env"]
    cmds:
      - docker compose --profile L1 down -v
      - task: up
        vars: { PROFILE: "--profile L1" }
      - go test -v -tags=TEST_L1 ./...
      - task: down
        vars: { PROFILE: "--profile L1" }

  lint:
    cmds:
      - golangci-lint run

  gen_public_api:
    cmds:
     - swag init -g ./internal/port/http/public/doc.go -o ./api/http/public -ot json