// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	entities "crypto_service/internal/entities"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// GetAggregatedCoins mocks base method.
func (m *MockStorage) GetAggregatedCoins(ctx context.Context, titles []string, aggregationType string) ([]*entities.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAggregatedCoins", ctx, titles, aggregationType)
	ret0, _ := ret[0].([]*entities.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAggregatedCoins indicates an expected call of GetAggregatedCoins.
func (mr *MockStorageMockRecorder) GetAggregatedCoins(ctx, titles, aggregationType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAggregatedCoins", reflect.TypeOf((*MockStorage)(nil).GetAggregatedCoins), ctx, titles, aggregationType)
}

// GetAllTitles mocks base method.
func (m *MockStorage) GetAllTitles(ctx context.Context) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllTitles", ctx)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllTitles indicates an expected call of GetAllTitles.
func (mr *MockStorageMockRecorder) GetAllTitles(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllTitles", reflect.TypeOf((*MockStorage)(nil).GetAllTitles), ctx)
}

// GetCoinsByTitles mocks base method.
func (m *MockStorage) GetCoinsByTitles(ctx context.Context, titles []string) ([]*entities.Coin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLastCoins", ctx, titles)
	ret0, _ := ret[0].([]*entities.Coin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCoinsByTitles indicates an expected call of GetCoinsByTitles.
func (mr *MockStorageMockRecorder) GetLastCoins(ctx, titles interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLastCoins", reflect.TypeOf((*MockStorage)(nil).GetCoinsByTitles), ctx, titles)
}

// Store mocks base method.
func (m *MockStorage) Store(ctx context.Context, coins []*entities.Coin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", ctx, coins)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockStorageMockRecorder) Store(ctx, coins interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockStorage)(nil).Store), ctx, coins)
}
