FROM golang:1.26-alpine AS builder

WORKDIR /common

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o coin ./cmd/app/main.go

FROM alpine:latest AS coin_service

WORKDIR /app

COPY --from=builder /common/coin .
COPY --from=builder /common/config/coin.yaml .

CMD ["./coin", "--config=coin.yaml"]

#v1
# FROM golang:1.26-alpine AS builder
# WORKDIR /common
# RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2
# COPY ../../.golangci.yml ./
# COPY go.mod go.sum ./
# RUN go mod download
# COPY . .
# RUN golangci-lint run -c /common/.golangci.yml
# RUN go test ./...
# FROM builder AS coin_builder
# WORKDIR /common/coin
# RUN go build -o ./cmd/app/coin ./cmd/app/main.go
# FROM alpine:latest AS coin_service
# WORKDIR /app
# COPY --from=coin_builder /common/coin/cmd/app/coin .
# COPY --from=coin_builder /common/config/coin.yaml .
# CMD ["./coin","--config=coin.yaml"]
