FROM golang:1.26-alpine AS builder

WORKDIR /common

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o coin ./cmd/app/main.go

FROM alpine:latest AS coin_service

WORKDIR /app

COPY --from=builder /common/coin .
COPY --from=builder /common/config/coin.yaml .

CMD ["./coin", "--config=coin.yaml"]