service_name: coin_service
version: 1.0

port: 
  http:
    public:
      port: 9001
      timeout: 3s
client:
  timeout: 2s
storage:
  type: postgres
postgres:
  connection_string: postgres://postgres:postgres@db:5432/app?sslmode=disable
cron:
  actualize:
    interval: 5m
    timeout: 3s
tracing:
  jaeger: jaeger:4318
  switch_on: true
